'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';

export default function AdblockPage() {
  const search = useSearchParams();
  const siteId = search.get('siteId');
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  useEffect(() => {
    if (!siteId) return;
    let active = true;
    async function load() { try { const response = await fetch(`/api/adblock?siteId=${encodeURIComponent(siteId)}`, { cache: 'no-store' }); if (!response.ok) throw new Error('Unable to load ad-block data'); const next = await response.json(); if (active) { setData(next); setError(''); } } catch (err) { if (active) setError(err instanceof Error ? err.message : 'Unable to load ad-block data'); } }
    load(); const timer = setInterval(load, 8000); return () => { active = false; clearInterval(timer); };
  }, [siteId]);
  if (!siteId) return <div className="text-ink-400 text-sm">Select a site.</div>;
  if (error && !data) return <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!data) return <div className="text-ink-400 text-sm">Loading ad-block diagnostics…</div>;
  const totals = data.totals || {};
  const methods = data.byMethod || [];
  const vendors = data.byVendor || [];
  const recent = data.recent || [];
  const telemetryRecent = data.telemetryRecent || [];
  const candidates = data.candidates || [];
  const blockedSessions = Number(totals.blocked_sessions_24h) || 0;
  const totalSessions = Number(totals.total_sessions_24h) || 0;
  const rate = totals.confirmed_rate_pct == null ? (totalSessions < Number(totals.min_sample_size || 30) ? `Collecting (${totalSessions}/${Number(totals.min_sample_size || 30)})` : '—') : `${Number(totals.confirmed_rate_pct).toFixed(1)}%`;
  return (
    <div className="fade-in max-w-6xl">
      <div className="mb-6"><h2 className="text-lg font-semibold text-ink-950">Ad-blocker impact</h2><p className="text-sm text-ink-500 mt-1">Confirmed and likely signals are based on explicit browser-blocking evidence. Correlation gaps and GAfix collector delivery gaps are diagnostic signals only and are never counted as proof of ad blocking.</p></div>
      {error && <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Live refresh paused: {error}</div>}
      <div className="grid md:grid-cols-5 gap-4 mb-6"><Metric label="Confirmed rate" value={rate} detail="Distinct confirmed sessions" /><Metric label="Confirmed sessions" value={blockedSessions.toLocaleString()} detail={`${Number(totals.blocked_events_24h || 0).toLocaleString()} confirmed signals in 24h`} /><Metric label="Confirmed event reports" value={Number(totals.blocked_event_reports_24h || 0).toLocaleString()} detail="Confirmed blocker evidence with an event" /><Metric label="Correlation gaps" value={Number(totals.correlation_gaps_24h || 0).toLocaleString()} detail="Needs network verification" /><Metric label="Vendors affected" value={vendors.length.toLocaleString()} detail="Confirmed vendor families" /></div>
      <div className="grid lg:grid-cols-2 gap-6 mb-6">
        <section className="bg-white rounded-xl border border-ink-200 p-5"><h3 className="font-semibold text-ink-950 mb-4">Signal breakdown</h3>{methods.length ? <div className="space-y-3">{methods.map((method: any) => <div key={`${method.detection_method}-${method.signal}`}><div className="flex justify-between text-sm mb-1"><span>{describeMethod(method.detection_method, method.confidence)} <span className="text-xs text-ink-400">({method.signal || 'signal'})</span></span><span className="font-medium">{Number(method.cnt).toLocaleString()} · {Number(method.sessions).toLocaleString()} sessions</span></div><div className="h-2 rounded-full bg-ink-100 overflow-hidden"><div className="h-full bg-brand-500" style={{ width: `${Math.min(100, Number(method.cnt) / Math.max(1, Number(methods[0].cnt)) * 100)}%` }} /></div></div>)}</div> : <p className="text-sm text-ink-400">No ad-block signals yet.</p>}</section>
        <section className="bg-white rounded-xl border border-ink-200 p-5"><h3 className="font-semibold text-ink-950 mb-4">Blocked vendor coverage</h3>{vendors.length ? <div className="space-y-3">{vendors.map((vendor: any) => <div key={vendor.vendor} className="flex items-center justify-between text-sm"><span className="uppercase mono">{vendor.vendor}</span><span className="font-medium">{Number(vendor.cnt).toLocaleString()} signals</span></div>)}</div> : <p className="text-sm text-ink-400">Vendor attribution will appear as blocked URLs are observed.</p>}</section>
      </div>
      <section className="bg-white rounded-xl border border-ink-200"><div className="p-4 border-b border-ink-100"><h3 className="font-semibold text-ink-950">Recent blocker evidence</h3><p className="text-xs text-ink-500 mt-1">Only confirmed or likely browser-blocking evidence appears here. Correlation gaps are retained for investigation, but lifecycle events such as consent callbacks are excluded.</p></div>{recent.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs text-ink-500 uppercase bg-ink-50"><tr><th className="text-left px-4 py-2">Time</th><th className="text-left px-4 py-2">Signal</th><th className="text-left px-4 py-2">Event</th><th className="text-left px-4 py-2">Blocked URL</th><th className="text-left px-4 py-2">Page</th></tr></thead><tbody className="divide-y divide-ink-100">{recent.map((item: any, index: number) => <tr key={`${item.detected_at}-${index}`} className="hover:bg-ink-50"><td className="px-4 py-2 mono text-xs">{new Date(item.detected_at).toLocaleTimeString()}</td><td className="px-4 py-2"><span className={`pill ${item.confidence === 'confirmed' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'}`}>{describeMethod(item.detection_method, item.confidence)}</span></td><td className="px-4 py-2 mono text-xs">{item.event_name || '—'}</td><td className="px-4 py-2 mono text-xs truncate max-w-[260px]">{item.blocked_url || '—'}</td><td className="px-4 py-2 mono text-xs truncate max-w-[240px]">{item.page_url || '—'}</td></tr>)}</tbody></table></div> : <div className="p-8 text-center text-sm text-ink-400">No confirmed or likely blocker evidence in the last 24 hours.</div>}      </section>
      <section className="bg-white rounded-xl border border-ink-200 mt-6"><div className="p-4 border-b border-ink-100"><h3 className="font-semibold text-ink-950">Blocker pattern review queue</h3><p className="text-xs text-ink-500 mt-1">Recurring signals that do not yet meet explicit blocker evidence criteria. Review these patterns before promoting them into the confirmed or likely rule set.</p></div>{candidates.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs text-ink-500 uppercase bg-ink-50"><tr><th className="text-left px-4 py-2">Pattern</th><th className="text-left px-4 py-2">Vendor</th><th className="text-left px-4 py-2">Evidence</th><th className="text-left px-4 py-2">Samples</th><th className="text-left px-4 py-2">Last seen</th></tr></thead><tbody className="divide-y divide-ink-100">{candidates.map((item: any) => <tr key={`${item.detection_method}-${item.vendor}-${item.signal}`}><td className="px-4 py-2 mono text-xs">{item.detection_method} · {item.signal}</td><td className="px-4 py-2 uppercase mono text-xs">{item.vendor}</td><td className="px-4 py-2 mono text-xs max-w-[300px] truncate" title={item.raw_error || item.signal}>{item.raw_error || item.signal || '—'}</td><td className="px-4 py-2">{Number(item.sample_count).toLocaleString()}</td><td className="px-4 py-2 mono text-xs">{new Date(item.last_seen).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="p-8 text-center text-sm text-ink-400">No recurring unclassified blocker patterns are awaiting review.</div>}</section>
      <section className="bg-white rounded-xl border border-ink-200 mt-6"><div className="p-4 border-b border-ink-100"><h3 className="font-semibold text-ink-950">Monitor delivery health</h3><p className="text-xs text-ink-500 mt-1">These rows mean GAfix could not verify a vendor request or could not confirm collector delivery. They are not proof that an ad blocker is active.</p></div>{telemetryRecent.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs text-ink-500 uppercase bg-ink-50"><tr><th className="text-left px-4 py-2">Time</th><th className="text-left px-4 py-2">Diagnostic</th><th className="text-left px-4 py-2">Event</th><th className="text-left px-4 py-2">Request</th><th className="text-left px-4 py-2">Page</th></tr></thead><tbody className="divide-y divide-ink-100">{telemetryRecent.map((item: any, index: number) => <tr key={`${item.detected_at}-${index}`} className="hover:bg-ink-50"><td className="px-4 py-2 mono text-xs">{new Date(item.detected_at).toLocaleTimeString()}</td><td className="px-4 py-2"><span className="pill bg-ink-100 text-ink-700">{describeMethod(item.detection_method, item.confidence)}</span></td><td className="px-4 py-2 mono text-xs">{item.event_name || '—'}</td><td className="px-4 py-2 mono text-xs truncate max-w-[260px]">{item.blocked_url || '—'}</td><td className="px-4 py-2 mono text-xs truncate max-w-[240px]">{item.page_url || '—'}</td></tr>)}</tbody></table></div> : <div className="p-8 text-center text-sm text-ink-400">No collector or vendor-delivery gaps in the last 24 hours.</div>}</section>
    </div>
  );
}
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="bg-white p-4 rounded-xl border border-ink-200"><div className="text-xs text-ink-400 uppercase">{label}</div><div className="text-2xl font-semibold mt-1">{value}</div><div className="text-xs text-ink-500 mt-1">{detail}</div></div>; }
function describeMethod(method: string, confidence?: string) { const labels: Record<string, string> = { ga4_event_unmatched: 'GA4 event correlation gap', ga4_event_blocked: 'GA4 event correlation gap', ga4_transport_blocked: 'GA4 transport blocked', script_error: 'Monitor failed to load', script_timeout: 'Monitor load timeout', resource_error: 'Vendor resource error', ingest_transport_blocked: 'Telemetry delivery gap' }; const label = labels[method] || method || 'Unknown'; return confidence === 'correlation_gap' ? `${label} (verify network)` : confidence === 'telemetry_gap' ? `${label} (verify monitor delivery)` : confidence === 'likely' ? `${label} (likely blocker)` : label; }
