'use client';

import Link from 'next/link';
import { useEffect, useState, type CSSProperties } from 'react';
import FlowSummaryGraph from './dashboard/flow-summary';

const liveEvents = [
  { time: '09:42:18', vendor: 'GA4', event: 'purchase', status: '204', latency: '312 ms', tone: 'lime', path: 'client-side' },
  { time: '09:42:17', vendor: 'Meta', event: 'Purchase', status: '204', latency: '428 ms', tone: 'blue', path: 'client-side' },
  { time: '09:42:15', vendor: 'GA4', event: 'login', status: '200', latency: '188 ms', tone: 'violet', path: 'server-side' },
  { time: '09:42:11', vendor: 'Ads', event: 'generate_lead', status: '500', latency: '224 ms', tone: 'amber', path: 'server-side' },
];

const journeyChapters = [
  { id: 'observe', number: '01', eyebrow: 'Observe', title: 'See every signal as it moves.', text: 'Start with the Overview command center, then go one level deeper into GA4, Google Ads, Meta Pixel, and TikTok Pixel delivery.', features: ['Overview', 'Google Analytics 4', 'Google Ads', 'Meta Pixel', 'TikTok Pixel'], accent: 'lime' },
  { id: 'explain', number: '02', eyebrow: 'Explain', title: 'Turn suspicious data into a cause.', text: 'Sessions, revenue impact, Web Vitals, runtime audits, tag health, duplicate events, and GTM diagnostics connect the symptom to the firing path.', features: ['Sessions', 'Revenue impact', 'Web Vitals', 'Runtime audit', 'Tag health', 'Duplicate events', 'GTM diagnostics'], accent: 'blue' },
  { id: 'protect', number: '03', eyebrow: 'Protect', title: 'Know what privacy tools hide.', text: 'Ad-blocker impact, Consent Mode, Synthetic checks, and Compliance reveal where consent, browsers, blocked domains, and missing parameters create invisible risk.', features: ['Ad-blocker impact', 'Consent Mode', 'Synthetic checks', 'Compliance'], accent: 'rose' },
  { id: 'operate', number: '04', eyebrow: 'Operate', title: 'Move from alert to resolution.', text: 'Install the monitor manually or connect GTM, route evidence to Slack and signed webhooks, export operational records, and keep the workspace controlled.', features: ['Manual GTM install', 'Connect GTM', 'Integrations & exports', 'Settings'], accent: 'violet' },
];

const allFeatures = [
  { group: 'Monitoring', href: '/dashboard', label: 'Overview', detail: 'Command center' },
  { group: 'Monitoring', href: '/dashboard/ga4', label: 'Google Analytics 4', detail: 'Vendor analytics' },
  { group: 'Monitoring', href: '/dashboard/ads', label: 'Google Ads', detail: 'Conversion delivery' },
  { group: 'Monitoring', href: '/dashboard/meta', label: 'Meta Pixel', detail: 'Browser signals' },
  { group: 'Monitoring', href: '/dashboard/tiktok', label: 'TikTok Pixel', detail: 'Destination health' },
  { group: 'Insights', href: '/dashboard/sessions', label: 'Sessions', detail: 'Real-user journeys' },
  { group: 'Insights', href: '/dashboard/revenue', label: 'Revenue impact', detail: 'Conversion risk' },
  { group: 'Insights', href: '/dashboard/vitals', label: 'Web Vitals', detail: 'LCP · CLS · INP' },
  { group: 'Diagnostics', href: '/dashboard/audit', label: 'Runtime audit', detail: 'Browser evidence' },
  { group: 'Diagnostics', href: '/dashboard/health', label: 'Tag health', detail: 'Fires and failures' },
  { group: 'Diagnostics', href: '/dashboard/duplicates', label: 'Duplicate events', detail: 'Fan-out analysis' },
  { group: 'Diagnostics', href: '/dashboard/gtm', label: 'GTM diagnostics', detail: 'Trigger intelligence' },
  { group: 'Diagnostics', href: '/dashboard/adblock', label: 'Ad-blocker impact', detail: 'Blocked signals' },
  { group: 'Diagnostics', href: '/dashboard/consent', label: 'Consent Mode', detail: 'GCS / GCD context' },
  { group: 'Diagnostics', href: '/dashboard/synthetic', label: 'Synthetic checks', detail: 'Scheduled journeys' },
  { group: 'Diagnostics', href: '/dashboard/compliance', label: 'Compliance', detail: 'Privacy posture' },
  { group: 'Setup', href: '/dashboard/install', label: 'Manual GTM install', detail: 'Fallback path' },
  { group: 'Setup', href: '/dashboard/gtm-connect', label: 'Connect GTM', detail: 'Review and publish' },
  { group: 'Setup', href: '/dashboard/integrations', label: 'Integrations & exports', detail: 'Slack · webhooks · CSV' },
  { group: 'Setup', href: '/dashboard/settings', label: 'Settings', detail: 'Alert policy' },
];

export default function LandingPage() {
  const [activeChapter, setActiveChapter] = useState('observe');

  useEffect(() => {
    const chapters = Array.from(document.querySelectorAll<HTMLElement>('[data-gafix-chapter]'));
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
      if (visible?.target instanceof HTMLElement) setActiveChapter(visible.target.dataset.gafixChapter || 'observe');
    }, { rootMargin: '-35% 0px -45% 0px', threshold: [0.1, 0.4, 0.8] });
    chapters.forEach((chapter) => observer.observe(chapter));
    return () => observer.disconnect();
  }, []);

  return (
    <main className="min-h-screen overflow-hidden bg-[#070b12] text-white selection:bg-[#b8f56b] selection:text-[#07111f]">
      <nav className="sticky top-0 z-50 border-b border-white/[.08] bg-[#070b12]/85 text-white backdrop-blur-2xl">
        <div className="mx-auto flex h-[74px] max-w-7xl items-center justify-between px-5 lg:px-8">
          <Link href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl bg-white p-0.5 shadow-lg shadow-black/30"><img src="/gafix-logo.png" alt="GAfix" className="h-full w-full object-contain" /></span><span><span className="block text-lg font-semibold tracking-tight">GAfix<span className="text-[#b8f56b]">.</span></span><span className="block text-[9px] font-bold uppercase tracking-[.22em] text-slate-500">Real-user intelligence</span></span></Link>
          <div className="hidden items-center gap-7 text-sm text-slate-400 md:flex"><a href="#features" className="transition hover:text-white">Product map</a><a href="#flow" className="transition hover:text-white">Delivery flow</a><a href="#catalog" className="transition hover:text-white">All features</a><a href="#workflow" className="transition hover:text-white">Setup</a></div>
          <div className="flex items-center gap-3"><Link href="/login" className="hidden rounded-full px-4 py-2 text-sm text-slate-300 transition hover:bg-white/5 hover:text-white sm:block">Sign in</Link><Link href="/signup" className="rounded-full bg-[#b8f56b] px-5 py-2.5 text-sm font-bold text-[#07111f] shadow-[0_0_28px_rgba(184,245,107,.18)] transition hover:bg-[#d2ff9b] active:scale-[.98]">Start monitoring</Link></div>
        </div>
      </nav>

      <section className="relative isolate border-b border-white/[.08] bg-[#070b12]"><div className="gafix-hero-grid absolute inset-0 opacity-70" /><div className="absolute -left-32 top-16 h-96 w-96 rounded-full bg-[#6d8cff]/10 blur-3xl" /><div className="absolute right-[-12rem] top-24 h-[34rem] w-[34rem] rounded-full bg-[#b8f56b]/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-16 px-5 pb-20 pt-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#b8f56b]/25 bg-[#b8f56b]/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.16em] text-[#d8ffad]"><span className="gafix-pulse-dot h-2 w-2 rounded-full bg-[#b8f56b]" /> Live telemetry command center</div><h1 className="max-w-2xl text-5xl font-semibold leading-[.94] tracking-[-.065em] text-white sm:text-6xl lg:text-[78px]">Tracking should tell you what broke <span className="text-[#b8f56b]">before the report does.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-slate-400 sm:text-lg">GAfix watches real browsers, follows every event through the dataLayer and network, and turns delivery failures into evidence your analytics team can trust.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="rounded-full bg-[#b8f56b] px-6 py-3.5 text-center text-sm font-bold text-[#07111f] transition hover:bg-[#d2ff9b] active:scale-[.98]">Start with one site <span className="ml-1">→</span></Link><a href="#features" className="rounded-full border border-white/15 px-6 py-3.5 text-center text-sm font-semibold text-white transition hover:border-white/35 hover:bg-white/5">Explore the product map</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span>✓ GTM Connect or manual fallback</span><span>✓ First evidence in seconds</span><span>✓ Consent-aware by design</span></div></div><TelemetryStage /></div></section>

      <section id="features" className="border-b border-white/[.08] bg-[#0b111b] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="dashboard-eyebrow text-[#8fa8ff]">The complete GAfix product map</p><h2 className="mt-4 max-w-xl text-4xl font-semibold tracking-[-.05em] text-white sm:text-5xl">One active scene. Every capability in context.</h2></div><p className="max-w-xl text-base leading-7 text-slate-400">Choose a job and see the exact GAfix surfaces that support it. The product stays complete without turning the homepage into a wall of cards.</p></div><div className="gafix-feature-navigator mt-12"><div className="gafix-feature-tabs" role="tablist" aria-label="GAfix product layers">{journeyChapters.map((chapter) => <button key={chapter.id} type="button" role="tab" aria-selected={activeChapter === chapter.id} onClick={() => setActiveChapter(chapter.id)} className={`gafix-feature-tab ${activeChapter === chapter.id ? 'is-active' : ''}`}><span className="gafix-feature-tab-number">{chapter.number}</span><span className="gafix-feature-tab-copy"><strong>{chapter.eyebrow}</strong><small>{chapter.title}</small></span><span className="gafix-feature-tab-arrow">↗</span></button>)}</div><div className="min-w-0"><FeatureStage activeId={activeChapter} /></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 text-[10px] font-bold uppercase tracking-[.15em] text-slate-600"><span>20 connected feature surfaces</span><span>Observe · Explain · Protect · Operate</span></div></div></section>

      <section id="evidence" className="border-b border-white/[.08] bg-[#080d16] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="dashboard-eyebrow text-[#ff9aae]">Evidence, not assumptions</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] text-white sm:text-5xl">The timeline behind every alert.</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-400">When a conversion looks wrong, GAfix shows the browser event, the network call, the response, the consent signal, the session correlation, and the fix path in one place.</p><div className="mt-8 space-y-4"><ProofRow title="Vendor-aware" text="GA4, Ads, Meta, TikTok, and the broader vendor layer are labeled consistently." tone="lime" /><ProofRow title="Consent-aware" text="GCS/GCD network evidence is interpreted separately from defaults and cookieless measurement." tone="violet" /><ProofRow title="Session-safe" text="Repeated actions are correlated within a browser session without confusing separate visitors." tone="blue" /></div></div><EvidencePanel /></div></section>

      <section id="workflow" className="bg-[#070b12] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="dashboard-eyebrow text-[#8fa8ff]">A calm setup experience</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] text-white sm:text-5xl">From first install to confident alerting.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3"><Step n="01" title="Create a site" text="Add your domain and measurement IDs. GAfix creates a private evidence boundary for that site." /><Step n="02" title="Connect GTM" text="Use the recommended OAuth flow to create one monitor tag, review the workspace, and publish deliberately." /><Step n="03" title="Operate by evidence" text="Watch the live pulse, tune alert policy, verify Slack, and use the daily report for quieter signals." /></div><div className="mt-6 rounded-2xl border border-[#a8f06a]/15 bg-[#a8f06a]/[.06] p-5 text-sm text-[#cfff9d]"><strong>One installation rule:</strong> use Connect GTM, or the matching Manual GTM fallback. Never publish both monitor tags.</div></div></section>

      <section className="border-t border-white/[.08] bg-[#070b12] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="gafix-cta-card mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 rounded-[30px] border border-white/[.1] bg-[#111722] p-8 sm:p-12 lg:flex-row lg:items-center"><div><p className="dashboard-eyebrow text-[#b8f56b]">The next broken tag is already happening</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.05em] text-white sm:text-5xl">Stop finding out from the report.</h2><p className="mt-4 max-w-xl text-slate-400">Start with one site, one monitor tag, and an evidence timeline your team can trust.</p></div><Link href="/signup" className="shrink-0 rounded-full bg-[#b8f56b] px-7 py-3.5 text-sm font-bold text-[#07111f] transition hover:bg-[#d2ff9b] active:scale-[.98]">Start monitoring →</Link></div></section>
      <footer className="border-t border-white/[.08] bg-[#070b12] px-5 pb-10 text-sm text-slate-500 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 pt-7 sm:flex-row sm:items-center"><span>© 2026 GAfix · Real-user tag observability</span><div className="flex gap-5"><Link href="/login" className="transition hover:text-white">Sign in</Link><Link href="/signup" className="transition hover:text-white">Start free</Link><a href="https://github.com/PriyatoshKadam/manusai18081" className="transition hover:text-white">Source</a></div></div></footer>
    </main>
  );
}

function TelemetryStage() {
  return <div className="gafix-stage relative mx-auto w-full max-w-[700px] lg:ml-auto"><div className="gafix-stage-glow absolute inset-10 rounded-full bg-[#6d8cff]/10 blur-3xl" /><div className="gafix-stage-shell relative overflow-hidden rounded-[30px] border border-white/[.12] bg-[#0d1522]/90 p-4 shadow-2xl shadow-black/50 backdrop-blur-xl sm:p-5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(184,245,107,.12),transparent_32%),radial-gradient(circle_at_90%_80%,rgba(109,140,255,.12),transparent_34%)]" /><div className="relative flex items-center justify-between border-b border-white/[.08] pb-4"><div><div className="flex items-center gap-2"><span className="gafix-pulse-dot h-2 w-2 rounded-full bg-[#b8f56b]" /><span className="text-[10px] font-bold uppercase tracking-[.18em] text-[#cfff9d]">Live telemetry</span></div><p className="mt-2 text-sm font-semibold text-white">Real browser signal, moving now</p></div><span className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 font-mono text-[10px] text-slate-400">AUTO · 24H</span></div><div className="relative mt-4 grid grid-cols-3 gap-2 sm:gap-3"><StageMetric label="Fires / min" value="1,247" tone="lime" /><StageMetric label="Sessions" value="582" tone="blue" /><StageMetric label="At risk" value="₹18.4k" tone="rose" /></div><EventConveyor /><div className="relative mt-4 grid gap-3 sm:grid-cols-[1fr_1.25fr]"><div className="rounded-2xl border border-white/[.08] bg-white/[.03] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Delivery map</span><span className="text-[10px] text-[#8fa8ff]">2 paths</span></div><MiniFlow /></div><div className="rounded-2xl border border-[#ff718d]/20 bg-[#ff718d]/[.06] p-4"><div className="flex items-start gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#ff718d]/15 text-[#ff9aae]">!</span><div><p className="text-xs font-semibold text-white">Purchase delivery degraded</p><p className="mt-1 text-[11px] leading-5 text-slate-400">HTTP 500 · missing transaction_id · critical route</p></div></div><div className="mt-4 flex items-center justify-between text-[10px]"><span className="text-slate-500">Detection confidence</span><strong className="text-[#ff9aae]">94%</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="gafix-confidence-bar h-full w-[94%] rounded-full bg-[#ff718d]" /></div></div></div></div></div>;
}

function EventConveyor() {
  return <div className="gafix-conveyor relative mt-5 overflow-hidden rounded-2xl border border-white/[.08] bg-[#080d16]/95 p-3 sm:p-4"><div className="mb-4 flex items-center justify-between"><div><span className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Event conveyor</span><p className="mt-1 text-xs font-semibold text-white">New signals arrive, move, and become evidence</p></div><span className="font-mono text-[10px] text-[#b8f56b]">● receiving</span></div><div className="gafix-conveyor-head hidden grid-cols-[1fr_1fr_1fr_1fr] gap-2 px-2 pb-2 text-[9px] font-bold uppercase tracking-[.12em] text-slate-600 sm:grid"><span>Browser</span><span>Inspect</span><span>Destination</span><span>Alert bus</span></div><div className="gafix-conveyor-track"><div className="gafix-conveyor-route gafix-conveyor-route-one" /><div className="gafix-conveyor-route gafix-conveyor-route-two" /><div className="gafix-conveyor-route gafix-conveyor-route-three" /><div className="gafix-conveyor-station gafix-conveyor-station-browser"><span className="gafix-station-dot bg-[#b8f56b]" /><span>browser</span></div><div className="gafix-conveyor-station gafix-conveyor-station-inspect"><span className="gafix-station-dot bg-[#8fa8ff]" /><span>inspect</span></div><div className="gafix-conveyor-station gafix-conveyor-station-destination"><span className="gafix-station-dot bg-[#b18cff]" /><span>destination</span></div><div className="gafix-conveyor-station gafix-conveyor-station-alert"><span className="gafix-station-dot bg-[#ff718d]" /><span>alert</span></div>{[...liveEvents, ...liveEvents].map((event, index) => <div key={`${event.time}-${event.event}-${index}`} className={`gafix-conveyor-card ${event.status === '500' ? 'is-alert' : ''}`} style={{ animationDelay: `${index * 2.1}s` }}><span className="font-mono text-[9px] text-slate-600">{event.time}</span><span className={`h-1.5 w-1.5 shrink-0 rounded-full ${event.tone === 'lime' ? 'bg-[#b8f56b]' : event.tone === 'blue' ? 'bg-[#8fa8ff]' : event.tone === 'violet' ? 'bg-[#b18cff]' : 'bg-[#f6b94c]'}`} /><span className="font-semibold text-slate-200">{event.event}</span><span className="text-[9px] text-slate-500">{event.vendor}</span><span className={`ml-auto rounded-full px-1.5 py-1 text-[9px] font-bold ${event.status === '500' ? 'bg-[#ff718d]/15 text-[#ff9aae]' : 'bg-[#b8f56b]/10 text-[#cfff9d]'}`}>{event.status === '500' ? 'alert' : event.status}</span></div>)}</div><div className="mt-3 flex items-center justify-between rounded-xl border border-[#ff718d]/20 bg-[#ff718d]/[.06] px-3 py-2"><div className="flex items-center gap-2"><span className="gafix-alert-ping flex h-5 w-5 items-center justify-center rounded-full bg-[#ff718d]/20 text-[10px] font-bold text-[#ff9aae]">!</span><span className="text-[10px] font-semibold text-[#ffb1bf]">Alert detected: purchase delivery degraded</span></div><span className="font-mono text-[9px] text-[#ff9aae]">→ Slack · critical</span></div></div>;
}

function FeatureStage({ activeId }: { activeId: string }) {
  const active = journeyChapters.find((chapter) => chapter.id === activeId) || journeyChapters[0];
  const accent = active.accent === 'lime' ? '#b8f56b' : active.accent === 'blue' ? '#8fa8ff' : active.accent === 'rose' ? '#ff718d' : '#b18cff';
  const sceneMetrics = active.id === 'observe' ? [['vendors', '4'], ['signals', '1.2k'], ['paths', '2']] : active.id === 'explain' ? [['sessions', '582'], ['causes', '7'], ['evidence', 'live']] : active.id === 'protect' ? [['consent', 'GCS/GCD'], ['blocked', '34'], ['checks', '24/7']] : [['alerts', 'Slack'], ['exports', 'CSV'], ['setup', 'GTM']];
  return <div className="gafix-feature-stage" style={{ '--gafix-stage-accent': accent } as CSSProperties}><div className="gafix-feature-stage-top"><div><span className="font-mono text-xs font-bold" style={{ color: accent }}>{active.number}</span><p className="mt-4 text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Active scene · {active.eyebrow}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight text-white">{active.title}</h3></div><span className="gafix-scene-live"><span /> live scene</span></div><div className="gafix-feature-scene"><div className="gafix-scene-horizon" /><div className="gafix-scene-ring gafix-scene-ring-one" /><div className="gafix-scene-ring gafix-scene-ring-two" /><div className="gafix-scene-core"><span className="gafix-scene-core-mark">{active.number}</span><span className="gafix-scene-core-title">{active.eyebrow}</span><small>GAfix signal layer</small></div><div className="gafix-scene-route route-a" /><div className="gafix-scene-route route-b" /><div className="gafix-scene-route route-c" />{active.features.slice(0, 6).map((feature, index) => <span key={feature} className={`gafix-scene-node node-${index + 1}`}><i style={{ backgroundColor: accent }} />{feature}</span>)}<span className="gafix-scene-packet packet-one" style={{ backgroundColor: accent }} /><span className="gafix-scene-packet packet-two" style={{ backgroundColor: accent }} /></div><div className="gafix-feature-stage-bottom"><p className="max-w-md text-sm leading-6 text-slate-400">{active.text}</p><div className="grid grid-cols-3 gap-2">{sceneMetrics.map(([label, value]) => <div key={label} className="gafix-scene-metric"><span>{label}</span><strong>{value}</strong></div>)}</div></div><div className="gafix-feature-link-rail">{active.features.map((feature) => <span key={feature} className="gafix-feature-link"><i style={{ backgroundColor: accent }} />{feature}</span>)}</div></div>;
}

function StageMetric({ label, value, tone }: { label: string; value: string; tone: string }) { const text = tone === 'lime' ? 'text-[#cfff9d]' : tone === 'rose' ? 'text-[#ff9aae]' : 'text-[#aebcff]'; return <div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-3"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-slate-600">{label}</p><p className={`mt-2 text-xl font-semibold tracking-tight ${text}`}>{value}</p></div>; }
function MiniFlow() { return <div className="mt-5 space-y-4"><div className="gafix-flow-line"><div className="gafix-flow-label"><span className="h-2 w-2 rounded-full bg-[#f6b94c]" /> browser → platform</div><div className="gafix-flow-track"><span className="gafix-flow-packet gafix-flow-packet-amber" /></div></div><div className="gafix-flow-line"><div className="gafix-flow-label"><span className="h-2 w-2 rounded-full bg-[#b8f56b]" /> browser → edge → vendor</div><div className="gafix-flow-track"><span className="gafix-flow-packet gafix-flow-packet-lime" /></div></div><div className="mt-5 flex justify-between text-[9px] font-mono text-slate-600"><span>browser</span><span>destination</span></div></div>; }
function EvidencePanel() { const rows = [['dataLayer occurrence', 'event-1787210911'], ['network observations', '2 calls'], ['request status', '204 / 500'], ['consent signal', 'gcs G111 · granted'], ['probable cause', '2 tags / 1 trigger']]; return <div className="gafix-depth-card relative overflow-hidden rounded-[28px] border border-white/[.09] bg-[#111722] p-5 shadow-2xl shadow-black/30 sm:p-8"><div className="absolute right-[-4rem] top-[-4rem] h-48 w-48 rounded-full bg-[#ff718d]/10 blur-3xl" /><div className="relative flex items-center justify-between border-b border-white/[.08] pb-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Incident evidence</p><p className="mt-2 text-lg font-semibold text-white">login · GTM fan-out</p></div><span className="rounded-full bg-[#ff718d]/10 px-3 py-1 text-xs font-semibold text-[#ff9aae]">critical</span></div><div className="relative space-y-0 py-5">{rows.map(([label, value]) => <div key={label} className="flex items-center justify-between gap-4 border-b border-white/[.06] py-3 text-sm"><span className="text-slate-500">{label}</span><span className="font-mono text-right text-[11px] text-slate-200">{value}</span></div>)}</div><div className="relative rounded-xl border border-[#b8f56b]/20 bg-[#b8f56b]/10 p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#cfff9d]">Recommended fix</p><p className="mt-2 text-sm leading-6 text-slate-200">Open GTM Preview, inspect the login trigger, and keep only one GA4 Event tag on that firing path.</p></div></div>; }
function ProofRow({ title, text, tone }: { title: string; text: string; tone: string }) { const dot = tone === 'lime' ? 'bg-[#b8f56b] text-[#07111f]' : tone === 'violet' ? 'bg-[#b18cff] text-[#07111f]' : 'bg-[#6d8cff] text-[#07111f]'; return <div className="flex gap-3"><span className={`mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-xs font-bold ${dot}`}>✓</span><div><p className="font-semibold text-white">{title}</p><p className="mt-1 text-sm leading-6 text-slate-400">{text}</p></div></div>; }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="gafix-hover-lift rounded-[24px] border border-white/[.08] bg-[#111722] p-6"><span className="font-mono text-xs font-bold text-[#8fa8ff]">{n}</span><h3 className="mt-10 text-xl font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></div>; }
