export type GovernanceVendor = 'ga4' | 'gads' | 'meta' | 'bing' | 'tiktok' | 'linkedin' | 'snapchat';
export type GovernancePresence = 'required' | 'optional' | 'conditional';
export type GovernanceRule = { name: string; aliases?: string[]; type?: 'string' | 'number' | 'boolean' | 'array' | 'object'; presence: GovernancePresence; description?: string };
export type GovernanceEvent = { name: string; aliases?: string[]; category: 'standard' | 'conversion' | 'commerce' | 'lead' | 'engagement'; parameters: GovernanceRule[]; revenue?: boolean; dedupe?: string[] };

const r=(name:string,presence:GovernancePresence,type?:GovernanceRule['type'],aliases?:string[],description?:string):GovernanceRule=>({name,presence,type,aliases,description});
const e=(name:string,category:GovernanceEvent['category'],parameters:GovernanceRule[],options:Partial<GovernanceEvent>={})=>({name,category,parameters,...options});

const commerce=[r('currency','conditional','string'),r('value','conditional','number'),r('transaction_id','conditional','string',['transactionId']),r('items','optional','array'),r('item_id','optional','string'),r('item_name','optional','string'),r('quantity','optional','number')];
const ga4Commerce=[...commerce.map(x=>({...x,presence:x.name==='transaction_id'||x.name==='value'||x.name==='currency'?'required':x.presence})),r('tax','optional','number'),r('shipping','optional','number'),r('coupon','optional','string'),r('affiliation','optional','string')];

export const PLATFORM_GOVERNANCE: Record<GovernanceVendor,{label:string;events:GovernanceEvent[];common:GovernanceRule[]}> = {
 ga4:{label:'Google Analytics 4',common:[r('user_id','optional','string',['uid']),r('session_id','conditional','string',['sid']),r('engagement_time_msec','optional','number')],events:[
  e('purchase','commerce',ga4Commerce,{revenue:true,dedupe:['transaction_id']}),e('refund','commerce',[...ga4Commerce],{revenue:true,dedupe:['transaction_id']}),
  e('add_to_cart','commerce',[r('items','required','array'),r('currency','conditional','string'),r('value','conditional','number')]),e('remove_from_cart','commerce',[r('items','required','array')]),
  e('view_item','commerce',[r('items','required','array'),r('currency','conditional','string'),r('value','conditional','number')]),e('view_item_list','commerce',[r('items','required','array'),r('item_list_id','optional','string'),r('item_list_name','optional','string')]),
  e('select_item','commerce',[r('items','required','array'),r('item_list_id','optional','string'),r('item_list_name','optional','string')]),e('begin_checkout','commerce',[r('items','required','array'),r('currency','conditional','string'),r('value','conditional','number')]),
  e('add_payment_info','commerce',[r('currency','conditional','string'),r('value','conditional','number'),r('coupon','optional','string'),r('items','optional','array'),r('payment_type','optional','string')]),e('add_shipping_info','commerce',[r('currency','conditional','string'),r('value','conditional','number'),r('coupon','optional','string'),r('items','optional','array'),r('shipping_tier','optional','string')]),
  e('view_cart','commerce',[r('items','required','array'),r('currency','conditional','string'),r('value','conditional','number')]),e('view_promotion','commerce',[r('items','required','array'),r('creative_name','optional','string'),r('creative_slot','optional','string'),r('promotion_id','optional','string'),r('promotion_name','optional','string')]),e('select_promotion','commerce',[r('items','required','array'),r('creative_name','optional','string'),r('creative_slot','optional','string'),r('promotion_id','optional','string'),r('promotion_name','optional','string')]),
  e('login','engagement',[r('method','optional','string')]),e('sign_up','engagement',[r('method','optional','string')]),e('search','engagement',[r('search_term','required','string')]),e('generate_lead','lead',[r('currency','conditional','string'),r('value','conditional','number'),r('lead_source','optional','string')],{revenue:true}),e('select_content','engagement',[r('content_type','optional','string'),r('content_id','optional','string')]),e('share','engagement',[r('method','optional','string'),r('content_type','optional','string'),r('item_id','optional','string')])
 ]},
 gads:{label:'Google Ads',common:[r('conversion_id','required','string',['aw-id']),r('conversion_label','required','string',['label']),r('currency','conditional','string'),r('value','conditional','number'),r('transaction_id','optional','string',['oid']),r('gclid','conditional','string')],events:[
  e('conversion','conversion',[r('conversion_id','required','string',['aw-id']),r('conversion_label','required','string',['label']),r('value','conditional','number'),r('currency','conditional','string'),r('transaction_id','optional','string',['oid'])],{revenue:true,dedupe:['transaction_id']}),
  e('purchase','commerce',[r('value','required','number'),r('currency','required','string'),r('transaction_id','required','string',['oid']),r('items','optional','array'),r('ecomm_prodid','optional','string'),r('ecomm_pagetype','optional','string'),r('ecomm_totalvalue','optional','number')],{revenue:true,dedupe:['transaction_id']}),
  e('lead','lead',[r('conversion_id','required','string',['aw-id']),r('conversion_label','required','string',['label']),r('value','optional','number'),r('currency','conditional','string')]),
 ]},
 meta:{label:'Meta',common:[r('event_name','required','string',['ev']),r('event_id','required','string',['eid']),r('event_source_url','required','string'),r('action_source','required','string'),r('fbp','optional','string'),r('fbc','conditional','string')],events:[
  e('PageView','standard',[r('event_name','required','string',['ev']),r('event_id','required','string',['eid'])]),e('ViewContent','engagement',[r('content_ids','optional','array'),r('content_type','optional','string'),r('content_name','optional','string'),r('value','conditional','number'),r('currency','conditional','string')]),e('Search','engagement',[r('search_string','optional','string')]),
  e('AddToCart','commerce',[r('content_ids','optional','array'),r('content_type','optional','string'),r('contents','optional','array'),r('value','conditional','number'),r('currency','conditional','string')]),e('InitiateCheckout','commerce',[r('content_ids','optional','array'),r('contents','optional','array'),r('num_items','optional','number'),r('value','conditional','number'),r('currency','conditional','string')]),e('AddPaymentInfo','commerce',[r('content_ids','optional','array'),r('contents','optional','array'),r('value','conditional','number'),r('currency','conditional','string')]),
  e('Purchase','commerce',[r('value','required','number'),r('currency','required','string'),r('event_id','required','string',['eid']),r('content_ids','optional','array'),r('contents','optional','array'),r('order_id','optional','string')],{revenue:true,dedupe:['event_id','order_id']}),
  e('Lead','lead',[r('event_id','required','string',['eid']),r('value','optional','number'),r('currency','conditional','string'),r('lead_id','optional','string')]),e('CompleteRegistration','conversion',[r('event_id','required','string',['eid']),r('status','optional','string')]),e('Subscribe','conversion',[r('value','optional','number'),r('currency','conditional','string'),r('subscription_id','optional','string')])
 ]},
 bing:{label:'Microsoft Ads',common:[r('ti','required','string'),r('msclkid','conditional','string'),r('asc','conditional','string')],events:[
  e('pageLoad','standard',[r('ti','required','string')]),e('custom','conversion',[r('ec','optional','string',['event_category']),r('ea','optional','string',['event_action']),r('el','optional','string',['event_label']),r('ev','optional','number',['event_value']),r('gv','conditional','number',['revenue_value']),r('gc','conditional','string',['currency']),r('transaction_id','optional','string')],{revenue:true,dedupe:['transaction_id']}),
  e('purchase','commerce',[r('ea','optional','string',['event_action']),r('gv','required','number',['revenue_value']),r('gc','required','string',['currency']),r('transaction_id','required','string'),r('items','optional','array')],{revenue:true,dedupe:['transaction_id']}),e('subscribe','conversion',[r('ea','optional','string',['event_action']),r('gv','optional','number',['revenue_value']),r('gc','conditional','string',['currency'])])
 ]},
 tiktok:{label:'TikTok',common:[r('event','required','string'),r('event_id','required','string'),r('event_time','required','number'),r('event_source','required','string'),r('event_source_url','required','string'),r('pixel','required','string'),r('ttclid','conditional','string'),r('ttp','optional','string')],events:[
  e('PageView','standard',[]),e('ViewContent','engagement',[r('content_type','optional','string'),r('content_ids','optional','array'),r('currency','conditional','string'),r('value','conditional','number')]),e('Search','engagement',[r('query','optional','string',['search_string'])]),e('AddToCart','commerce',[r('content_type','optional','string'),r('content_id','optional','string'),r('contents','optional','array'),r('currency','conditional','string'),r('value','conditional','number'),r('quantity','optional','number')]),e('InitiateCheckout','commerce',[r('contents','optional','array'),r('currency','conditional','string'),r('value','conditional','number')]),
  e('Purchase','commerce',[r('currency','required','string'),r('value','required','number'),r('content_type','optional','string'),r('content_ids','optional','array'),r('contents','optional','array'),r('quantity','optional','number'),r('order_id','optional','string')],{revenue:true,dedupe:['event_id','order_id']}),e('CompletePayment','conversion',[r('currency','required','string'),r('value','required','number'),r('order_id','optional','string')],{revenue:true,dedupe:['event_id','order_id']}),e('SubmitForm','lead',[r('value','optional','number')]),e('Contact','lead',[r('value','optional','number')]),e('Subscribe','conversion',[r('value','optional','number'),r('currency','conditional','string')]),e('StartTrial','conversion',[r('value','optional','number'),r('currency','conditional','string')])
 ]},
 linkedin:{label:'LinkedIn',common:[r('pid','required','string'),r('li_fat_id','conditional','string'),r('conversion','required','string'),r('conversionHappenedAt','required','number'),r('eventId','required','string'),r('userIds','conditional','array')],events:[
  e('conversion','conversion',[r('conversion','required','string'),r('conversionHappenedAt','required','number'),r('eventId','required','string'),r('userIds','conditional','array'),r('conversionValue.amount','optional','number'),r('conversionValue.currencyCode','conditional','string')],{revenue:true,dedupe:['eventId']}),
  e('page_view','standard',[r('pid','required','string')]),e('lead','lead',[r('conversion','required','string'),r('conversionHappenedAt','required','number'),r('eventId','required','string'),r('userIds','conditional','array')]),e('purchase','commerce',[r('conversion','required','string'),r('conversionHappenedAt','required','number'),r('eventId','required','string'),r('conversionValue.amount','required','number'),r('conversionValue.currencyCode','required','string')],{revenue:true,dedupe:['eventId']})
 ]},
 snapchat:{label:'Snapchat',common:[r('pixel_id','required','string',['pid']),r('event_id','required','string'),r('event_source_url','optional','string')],events:[
  e('PAGE_VIEW','standard',[r('pixel_id','required','string',['pid'])]),e('VIEW_CONTENT','engagement',[r('item_ids','conditional','array'),r('item_category','conditional','string'),r('price','optional','number'),r('currency','conditional','string')]),e('ADD_CART','commerce',[r('item_ids','conditional','array'),r('item_category','conditional','string'),r('price','optional','number'),r('currency','conditional','string')]),e('START_CHECKOUT','commerce',[r('item_ids','optional','array'),r('price','optional','number'),r('currency','conditional','string')]),e('PURCHASE','commerce',[r('price','required','number'),r('currency','required','string'),r('transaction_id','optional','string'),r('item_ids','optional','array'),r('item_category','optional','string')],{revenue:true,dedupe:['event_id','transaction_id']}),e('SIGN_UP','engagement',[r('user_id','optional','string')]),e('SEARCH','engagement',[r('search_string','optional','string')]),e('SUBSCRIBE','conversion',[r('price','optional','number'),r('currency','conditional','string')])
 ]},
};

export function canonicalEvent(vendor: GovernanceVendor, raw: unknown): GovernanceEvent | undefined {
 const value=String(raw??'').trim(); if(!value)return undefined; const events=PLATFORM_GOVERNANCE[vendor]?.events||[]; const n=value.toLowerCase(); return events.find(x=>x.name.toLowerCase()===n||x.aliases?.some(a=>a.toLowerCase()===n));
}
export function canonicalParameter(event: GovernanceEvent|undefined, raw: unknown): GovernanceRule|undefined {
 const value=String(raw??'').trim().toLowerCase(); if(!event||!value)return undefined; return event.parameters.find(x=>x.name.toLowerCase()===value||x.aliases?.some(a=>a.toLowerCase()===value));
}
export function allRules(vendor: GovernanceVendor,eventName?:string):GovernanceRule[]{const p=PLATFORM_GOVERNANCE[vendor];if(!p)return[];const event=canonicalEvent(vendor,eventName||'');return [...p.common,...(event?.parameters||[])];}
