'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';

export default function IntegrationsPage() {
  const search = useSearchParams(); const siteId = search.get('siteId');
  const [webhooks, setWebhooks] = useState<any[]>([]); const [url, setUrl] = useState(''); const [secret, setSecret] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function load() { if (!siteId) return; const r = await fetch(`/api/webhooks?siteId=${encodeURIComponent(siteId)}`, { cache: 'no-store' }); const b = await r.json(); if (!r.ok) throw new Error(b.error || 'Unable to load integrations'); setWebhooks(b.webhooks || []); }
  useEffect(() => { load().catch((e) => setError(e.message)); }, [siteId]);
  async function save() { setError(''); setMessage(''); try { const r = await fetch('/api/webhooks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ siteId: Number(siteId), url, secret, eventTypes: ['alert'] }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error || 'Unable to save webhook'); setUrl(''); setSecret(''); setMessage('Signed webhook saved.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save webhook'); } }
  async function remove(id: number) { await fetch(`/api/webhooks?siteId=${siteId}&id=${id}`, { method: 'DELETE' }); await load(); }
  return <div className="fade-in max-w-5xl space-y-6"><div><div className="text-xs font-semibold uppercase tracking-wider text-brand-600">Integrations and exports</div><h2 className="text-2xl font-semibold text-ink-950 mt-1">Delivery and data access</h2><p className="text-sm text-ink-500 mt-2">Send incident payloads to your systems with an HMAC signature and export operational evidence as CSV. BigQuery is intentionally not included.</p></div>{message && <div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800">{message}</div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<section className="card p-5"><h3 className="font-semibold">Add signed alert webhook</h3><div className="grid md:grid-cols-2 gap-3 mt-3"><input className="border rounded-lg px-3 py-2 text-sm" placeholder="https://ops.example.com/ga4fix" value={url} onChange={(e) => setUrl(e.target.value)} /><input className="border rounded-lg px-3 py-2 text-sm" placeholder="Signing secret" type="password" value={secret} onChange={(e) => setSecret(e.target.value)} /></div><button onClick={save} className="mt-3 rounded-lg bg-ink-950 text-white px-4 py-2 text-sm font-semibold">Save webhook</button>{webhooks.length ? <div className="mt-4 divide-y divide-ink-100">{webhooks.map((hook) => <div key={hook.id} className="py-3 flex items-center justify-between gap-3"><span className="mono text-sm break-all">{hook.url}</span><button onClick={() => remove(hook.id)} className="text-xs text-red-600">Remove</button></div>)}</div> : <p className="text-sm text-ink-400 mt-4">No webhooks configured.</p>}</section><section className="card p-5"><h3 className="font-semibold">Evidence exports</h3><p className="text-sm text-ink-500 mt-1">Exports are site-scoped and limited to operational history windows.</p><div className="flex flex-wrap gap-2 mt-4">{['events','alerts','revenue','synthetic'].map((kind) => <a key={kind} href={`/api/export?siteId=${encodeURIComponent(siteId || '')}&kind=${kind}&format=csv`} className="rounded-lg border border-ink-300 px-3 py-2 text-sm hover:bg-ink-50">Export {kind} CSV</a>)}</div></section></div>;
}
