'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';

export default function CompliancePage() {
  const search = useSearchParams(); const siteId = search.get('siteId');
  const [data, setData] = useState<any>({ findings: [], allowlist: [] }); const [hostname, setHostname] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function load() { if (!siteId) return; const r = await fetch(`/api/compliance?siteId=${encodeURIComponent(siteId)}`, { cache: 'no-store' }); const b = await r.json(); if (!r.ok) throw new Error(b.error || 'We could not load website safety information'); setData(b); }
  useEffect(() => { load().catch((e) => setError(e.message)); }, [siteId]);
  async function add() { setMessage(''); setError(''); try { const r = await fetch('/api/compliance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ siteId: Number(siteId), hostname }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error || 'We could not approve this website address'); setHostname(''); setMessage('Website address approved.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'We could not approve this website address'); } }
  return <div className="fade-in max-w-6xl space-y-6"><div><div className="text-xs font-semibold uppercase tracking-wider text-brand-600">Website safety</div><h2 className="text-2xl font-semibold text-ink-950 mt-1">Website safety checks</h2><p className="text-sm text-ink-500 mt-2">GAfix lists unfamiliar scripts, failed resources, and browser permission issues that may need review. Approving a website address does not hide delivery problems.</p></div>{message && <div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800">{message}</div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<section className="card p-5"><h3 className="font-semibold">Approve a trusted website address</h3><div className="flex gap-3 mt-3"><input className="border rounded-lg px-3 py-2 text-sm flex-1" placeholder="cdn.example.com" value={hostname} onChange={(e) => setHostname(e.target.value)} /><button onClick={add} className="rounded-lg bg-ink-950 text-white px-4 py-2 text-sm font-semibold">Approve address</button></div><div className="flex flex-wrap gap-2 mt-4">{data.allowlist?.map((item: any) => <span key={item.id} className="pill bg-green-100 text-green-800">{item.hostname}</span>)}</div></section><section className="card overflow-hidden"><div className="p-4 border-b border-ink-100"><h3 className="font-semibold">Issues to review</h3></div>{data.findings?.length ? <div className="divide-y divide-ink-100">{data.findings.map((item: any) => <div key={item.id} className="p-4"><div className="flex items-center gap-2"><span className="pill bg-red-100 text-red-800">{item.severity}</span><span className="font-medium">{item.category}</span></div><div className="text-sm text-ink-700 mt-2 break-all">{item.resource_url || item.page_url || 'No website address recorded'}</div><div className="text-xs text-ink-500 mt-1">Last seen {new Date(item.last_seen).toLocaleString()}</div></div>)}</div> : <div className="p-8 text-center text-sm text-ink-400">No website safety issues found.</div>}</section></div>;
}
