'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';

type Tab = 'overview' | 'events' | 'parameters' | 'pages' | 'consent' | 'adblocks';
type StatusFilter = 'All' | 'Healthy' | 'Needs attention' | 'New event' | 'Blocked';
const platformLabels: Record<string,string> = { ga4:'Google Analytics 4', gads:'Google Ads', meta:'Meta', bing:'Microsoft Ads', tiktok:'TikTok', linkedin:'LinkedIn', snapchat:'Snapchat' };
const eventLabel=(e:any)=>e.event_name||'Unnamed event';
const eventType=(e:any)=>String(e.event_type||'').toLowerCase()==='custom'?'Custom':'Standard';
const fmt=(v:any)=>Number(v||0).toLocaleString();
function statusForEvent(e:any,alerts:any[]):StatusFilter { const related=alerts.filter(a=>a.event_name===e.event_name); if(Number(e.blocked||0)>0)return'Blocked'; if(Number(e.failed||0)>0||related.some(a=>a.severity==='critical'))return'Needs attention'; if(related.some(a=>/new_event|new event/i.test(`${a.code||''} ${a.message||''}`)))return'New event'; return'Healthy'; }
function triggerForEvent(e:any){if(e.gtm_trigger_names?.length)return`GTM · ${e.gtm_trigger_names[0]}`;const n=String(e.event_name||'').toLowerCase();if(n.includes('click')||n.includes('cta'))return'CTA / click';if(n.includes('page_view')||n.includes('pageview')||n==='view_item'||n==='view')return'View';if(n.includes('custom'))return'Custom event';return'DataLayer';}
function noteForEvent(e:any,alerts:any[]){const r=alerts.filter(a=>a.event_name===e.event_name);if(Number(e.failed||0)>0)return`${fmt(e.failed)} failed deliveries.`;if(Number(e.blocked||0)>0)return`${fmt(e.blocked)} deliveries blocked.`;if(r[0])return r[0].message||r[0].code||'Issue detected.';return'No issue detected.';}
function Sparkline({values}:{values:number[]}){const p=values.length?values:[0,0],max=Math.max(...p,1),min=Math.min(...p,0),span=Math.max(max-min,1),path=p.map((v,i)=>`${i/Math.max(p.length-1,1)*100},${94-(v-min)/span*84}`).join(' ');return<svg width="76" height="28" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={path} fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round"/></svg>}
function LineGraph({points}:{points:any[]}){const width=720,height=210,pad=22,max=Math.max(...points.flatMap(p=>[Number(p.successful||0),Number(p.blocked||0)]),1),coords=(k:string)=>points.map((p,i)=>`${pad+i/Math.max(points.length-1,1)*(width-pad*2)},${height-pad-Number(p[k]||0)/max*(height-pad*2)}`).join(' ');return<div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-[250px] min-w-[720px] w-full"><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad} stroke="var(--border)"/><polyline points={coords('successful')} fill="none" stroke="#16a34a" strokeWidth="3"/><polyline points={coords('blocked')} fill="none" stroke="#f97316" strokeWidth="3"/></svg></div>}

export default function VendorView({vendor,label,id}:{vendor:string;label:string;id:string|null}){
 const search=useSearchParams(),siteId=search.get('siteId')||''; const [tab,setTab]=useState<Tab>('overview'); const [eventStatus,setEventStatus]=useState<StatusFilter>('All'); const [parameterStatus,setParameterStatus]=useState<'All'|'Healthy'|'Needs attention'>('All'); const [pageStatus,setPageStatus]=useState<'All'|'Healthy'|'Needs attention'>('All'); const [eventFilter,setEventFilter]=useState('All'); const [parameterFilter,setParameterFilter]=useState('All'); const [pageFilter,setPageFilter]=useState('All'); const [adblockEventFilter,setAdblockEventFilter]=useState('All'); const [loading,setLoading]=useState(true); const [data,setData]=useState<any>(null); const [traffic,setTraffic]=useState<any[]>([]); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(!siteId)return;let cancelled=false;setLoading(true);setError(null);Promise.all([fetch(`/api/events?siteId=${siteId}&vendor=${encodeURIComponent(vendor)}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('Unable to load event data'))),fetch(`/api/platform-insights?siteId=${siteId}&vendor=${encodeURIComponent(vendor)}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('Unable to load monitoring insights'))),fetch(`/api/platform-traffic?siteId=${siteId}&vendor=${encodeURIComponent(vendor)}`,{cache:'no-store'}).then(r=>r.ok?r.json():{trend:[]})]).then(([events,insights,tr])=>{if(cancelled)return;setData({...events,insights});setTraffic(tr.trend||[])}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Unable to load monitoring data')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[siteId,vendor]);
 const events=data?.events||[],alerts=(data?.alerts||[]).filter((a:any)=>!a.vendor||a.vendor===vendor),insights=data?.insights||{},overview=insights.overview||{},parameters=insights.parameters||[],pages=insights.pages||[],consent=insights.consent||{},adblocks=insights.adblocks||{};
 const eventNames=useMemo(()=>['All',...Array.from(new Set(events.map(eventLabel)))],[events]); const pageNames=useMemo(()=>['All',...Array.from(new Set(pages.map((r:any)=>r.page_path)))],[pages]); const adblockEventNames=useMemo(()=>['All',...Array.from(new Set((adblocks.rows||[]).map((r:any)=>r.event_name)))],[adblocks.rows]);
 const trendsByEvent=useMemo(()=>{const m=new Map<string,number[]>();for(const r of insights.eventTrends||[])m.set(r.event_name,[...(m.get(r.event_name)||[]),Number(r.count||0)]);return m},[insights.eventTrends]);
 const parameterRows=useMemo(()=>{const map=new Map<string,any>();for(const r of parameters){const name=String(r.parameter_name||'').toLowerCase();if(name)map.set(name,{...r,parameter_name:name,passing_events:r.passing_events||[],failing_events:r.failing_events||[]})}for(const e of events){const observed=Array.isArray(e.observed_parameters)?e.observed_parameters:[];const missing=Array.isArray(e.missing_parameters)?e.missing_parameters:[];for(const raw of [...observed,...missing]){const name=String(raw||'').trim().toLowerCase();if(!name)continue;const row=map.get(name)||{parameter_name:name,reference_event_count:0,mandatory_event_count:0,missing_event_count:0,passing_events:[],failing_events:[]};const eventName=eventLabel(e);if(observed.some((x:any)=>String(x).trim().toLowerCase()===name)){if(!row.passing_events.includes(eventName))row.passing_events.push(eventName);row.reference_event_count=(row.reference_event_count||0)+1}if(missing.some((x:any)=>String(x).trim().toLowerCase()===name)){if(!row.failing_events.includes(eventName))row.failing_events.push(eventName);row.missing_event_count=(row.missing_event_count||0)+1}row.mandatory_event_count=(row.mandatory_event_count||0)+1;map.set(name,row)}}for(const a of alerts){const text=`${a.code||''} ${a.message||''}`;const match=text.match(/(?:parameter|param)[^a-z0-9_]+([a-zA-Z0-9_.-]+)/i);if(match){const name=match[1].toLowerCase();const row=map.get(name)||{parameter_name:name,reference_event_count:0,mandatory_event_count:0,missing_event_count:0,passing_events:[],failing_events:[]};row.issueMessage=a.message||a.code||'Parameter issue detected.';row.isNew=/new/i.test(text)||row.isNew;map.set(name,row)}}return Array.from(map.values()).map(r=>({...r,coverage:r.mandatory_event_count?Math.round((Number(r.reference_event_count||0)/Number(r.mandatory_event_count))*1000)/10:100})).sort((a,b)=>Number(b.missing_event_count||0)-Number(a.missing_event_count||0)||String(a.parameter_name).localeCompare(String(b.parameter_name)))},[parameters,events,alerts]);
 const parameterNames=useMemo(()=>['All',...parameterRows.map(r=>r.parameter_name)],[parameterRows]); const filteredEvents=events.filter((e:any)=>eventFilter==='All'||eventLabel(e)===eventFilter).filter((e:any)=>eventStatus==='All'||statusForEvent(e,alerts)===eventStatus); const filteredParameters=parameterRows.filter((r:any)=>parameterFilter==='All'||r.parameter_name===parameterFilter).filter((r:any)=>parameterStatus==='All'||(r.isNew?'Needs attention':Number(r.missing_event_count)>0||Number(r.coverage)<100?'Needs attention':'Healthy')===parameterStatus); const filteredPages=pages.filter((r:any)=>pageFilter==='All'||r.page_path===pageFilter).filter((r:any)=>pageStatus==='All'||(Number(r.events)>0?'Healthy':'Needs attention')===pageStatus); const filteredBlocked=(adblocks.rows||[]).filter((r:any)=>adblockEventFilter==='All'||r.event_name===adblockEventFilter);
 const consentIssues=useMemo(()=>{const rows=[...(consent.eventsOutsideConsent||[])];for(const e of events){const s=e.consent_state||{};const choice=String(s.choice_recorded||'').toLowerCase()==='true';const denied=String(s.analytics_storage||'').toLowerCase()==='denied'||String(s.ad_storage||'').toLowerCase()==='denied';if(!choice&&denied&&!rows.some((r:any)=>r.event_name===eventLabel(e)&&r.vendor===vendor))rows.push({status:'Needs review',event_name:eventLabel(e),vendor,compliant:false,gtm_tag_name:e.gtm_tag_name||e.gtm_tag_names?.[0],notes:'Event fired while consent had not been recorded and storage was denied. Review the consent trigger/blocking rule.'})}return rows},[consent.eventsOutsideConsent,events,vendor]);
 const newIssues=alerts.filter((a:any)=>!a.created_at||new Date(a.created_at).getTime()>=Date.now()-86400000).length,stillOpen=alerts.filter((a:any)=>!a.resolved).length,newEventTypes=alerts.filter((a:any)=>/new_event|new event/i.test(`${a.code||''} ${a.message||''}`)).length,totalEventHits=Number(overview.total_event_hits||data?.stats?.events_24h||0),activeVendor=platformLabels[vendor]||label;
 if(!siteId)return<EmptyState title="Select a website" text="Choose a website from the dashboard sidebar to view platform monitoring."/>;if(loading&&!data)return<LoadingState label={`Loading ${activeVendor} monitoring…`}/>;if(error&&!data)return<EmptyState title="Monitoring data unavailable" text={error}/>;
 return <div className="fade-in mx-auto max-w-[1500px] space-y-5"><header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="dashboard-eyebrow">Platform monitoring</p><div className="mt-1 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--mon-tint)] text-xs font-bold text-[var(--mon-fg)]">{activeVendor.slice(0,2).toUpperCase()}</span><div><h2 className="font-display text-2xl font-semibold tracking-tight text-[var(--text)]">{activeVendor}</h2><p className="text-xs text-[var(--text-3)]">{id?`Destination ${id}`:'Destination configuration not detected'} · last 24 hours</p></div></div></div><Link href={`/dashboard/alerts?siteId=${siteId}`} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-2.5 text-xs font-semibold text-[var(--text)]">View alerts →</Link></header>
 <nav className="flex gap-1 overflow-x-auto rounded-xl border border-[var(--border)] bg-[var(--surface)] p-1">{([['overview','Overview'],['events','Events'],['parameters','Parameters'],['pages','Pages'],['consent','Consent'],['adblocks','Ad blockers']] as Array<[Tab,string]>).map(([key,name])=><button key={key} type="button" onClick={()=>setTab(key)} className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold" style={{background:tab===key?'var(--mon-tint)':'transparent',color:tab===key?'var(--mon-fg)':'var(--text-2)'}}>{name}</button>)}</nav>
 {tab==='overview'&&<section className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Total event hits" value={fmt(totalEventHits)}/><Kpi label="Event total" value={fmt(overview.event_total||events.length)}/><Kpi label="Parameters number" value={fmt(parameterRows.length)}/><Kpi label="New issues" value={fmt(newIssues)} tone="warn"/><Kpi label="Still open" value={fmt(stillOpen)} tone={stillOpen?'warn':'ok'}/><Kpi label="New event type detected" value={fmt(newEventTypes)} tone={newEventTypes?'info':'ok'}/></div><div className="grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><Panel title="Platform health"><div className="grid gap-3 sm:grid-cols-3"><HealthMetric label="Successful network events" value={fmt(overview.successful_network_events)}/><HealthMetric label="Failed network events" value={fmt(overview.failed_network_events)} warn={Number(overview.failed_network_events)>0}/><HealthMetric label="Open alerts" value={fmt(stillOpen)} warn={stillOpen>0}/></div></Panel><Panel title="What needs attention">{alerts.slice(0,5).map((a:any,i:number)=><div key={a.id||i} className="flex gap-3 border-b border-[var(--border-soft)] py-3"><span className="mt-1 h-2 w-2 rounded-full" style={{background:a.severity==='critical'?'#dc2626':'#f59e0b'}}/><div><div className="text-xs font-semibold">{a.event_name||a.code||'Tracking issue'}</div><div className="text-[11px] text-[var(--text-2)]">{a.message||a.code||'Review this alert.'}</div></div></div>)}{!alerts.length?<Empty text="No open platform alerts."/>:null}</Panel></div></section>}
 {tab==='events'&&<section className="space-y-3"><SectionHeader title="Events" subtitle="Every observed event, trigger, GTM correlation, volume and issue."><FilterSelect label="Event name" value={eventFilter} values={eventNames} onChange={setEventFilter}/><RadioFilter value={eventStatus} values={['All','Healthy','Needs attention','New event','Blocked']} onChange={v=>setEventStatus(v as StatusFilter)}/></SectionHeader><Table><thead><tr><Th>Status</Th><Th>Event Name</Th><Th>Trigger</Th><Th>GTM</Th><Th>Event Count</Th><Th>Notes</Th></tr></thead><tbody>{filteredEvents.map((e:any,i:number)=>{const st=statusForEvent(e,alerts);return<tr key={`${eventLabel(e)}-${i}`}><Td><StatusPill status={st}/></Td><Td><div className="font-mono text-xs font-semibold">{eventLabel(e)}</div><span className="mt-1 inline-block rounded-full bg-[var(--surface-3)] px-1.5 py-0.5 text-[9px] text-[var(--text-3)]">{eventType(e)}</span></Td><Td><span className="text-xs">{triggerForEvent(e)}</span></Td><Td><div className="text-[11px] font-medium">{e.gtm_tag_names?.join(', ')||'—'}</div><div className="text-[10px] text-[var(--text-3)]">{e.gtm_trigger_names?.join(', ')||'—'}</div></Td><Td><div className="flex items-center gap-2"><span className="font-semibold">{fmt(e.cnt)}</span><span className="w-[76px] text-[var(--mon-fg)]"><Sparkline values={trendsByEvent.get(String(e.event_name).toLowerCase())||[]}/></span></div></Td><Td><span className="text-[11px] text-[var(--text-2)]">{noteForEvent(e,alerts)}</span></Td></tr>})}</tbody></Table>{!filteredEvents.length?<Empty text="No events match the current filters."/>:null}</section>}
 {tab==='parameters'&&<section className="space-y-3"><SectionHeader title="Parameters" subtitle="Every observed parameter plus every missing, empty, or newly detected parameter issue."><FilterSelect label="Parameter" value={parameterFilter} values={parameterNames} onChange={setParameterFilter}/><RadioFilter value={parameterStatus} values={['All','Healthy','Needs attention']} onChange={v=>setParameterStatus(v as any)}/></SectionHeader><Table><thead><tr><Th>Status</Th><Th>Parameter Name</Th><Th>Reference Event</Th><Th>Coverage</Th><Th>Notes</Th></tr></thead><tbody>{filteredParameters.map((r:any)=><tr key={r.parameter_name}><Td><StatusPill status={r.isNew||Number(r.missing_event_count)>0||Number(r.coverage)<100?'Needs attention':'Healthy'}/></Td><Td><span className="font-mono text-xs font-semibold">{r.parameter_name}</span></Td><Td><span className="cursor-help border-b border-dashed border-[var(--border-strong)] text-xs font-semibold" title={(r.passing_events||[]).join(', ')||'No passing event observed'}>{fmt(r.reference_event_count)}</span><span className="ml-1 text-[10px] text-[var(--text-3)]">of {fmt(r.mandatory_event_count)}</span></Td><Td><div className="flex items-center gap-2"><div className="h-1.5 w-28 overflow-hidden rounded-full bg-[var(--surface-3)]"><div className="h-full rounded-full" style={{width:`${Math.min(100,Math.max(0,Number(r.coverage)||0))}%`,background:Number(r.coverage)>=100?'#16a34a':'#f59e0b'}}/></div><span className="text-xs font-semibold">{Number(r.coverage||0).toFixed(1)}%</span></div></Td><Td><span className="text-[11px] text-[var(--text-2)]">{r.issueMessage||((r.failing_events||[]).length?`${r.failing_events.join(', ')}: missing or empty.`:(r.isNew?'New parameter detected.':'Passed in the reference events.'))}</span></Td></tr>)}</tbody></Table>{!filteredParameters.length?<Empty text="No parameter evidence has been observed yet."/>:null}</section>}
 {tab==='pages'&&<section className="space-y-3"><SectionHeader title="Pages" subtitle="Page paths with event volume, sessions and observed session duration."><FilterSelect label="Page path" value={pageFilter} values={pageNames} onChange={setPageFilter}/><RadioFilter value={pageStatus} values={['All','Healthy','Needs attention']} onChange={v=>setPageStatus(v as any)}/></SectionHeader><Table><thead><tr><Th>Status</Th><Th>Page Path</Th><Th>Event Count</Th><Th>Sessions</Th><Th>Session Duration</Th><Th>Notes</Th></tr></thead><tbody>{filteredPages.map((r:any)=><tr key={r.page_path}><Td><StatusPill status={Number(r.events)>0?'Healthy':'Needs attention'}/></Td><Td><span className="font-mono text-xs font-semibold">{r.page_path}</span></Td><Td><span className="text-xs font-semibold">{fmt(r.events)}</span></Td><Td><span className="text-xs">{fmt(r.sessions)}</span></Td><Td><span className="text-xs">{formatDuration(Number(r.session_duration_seconds||0))}</span></Td><Td><span className="text-[11px] text-[var(--text-2)]">{Number(r.events)>0?'Events observed on this page.':'No event evidence observed.'}</span></Td></tr>)}</tbody></Table>{!filteredPages.length?<Empty text="No page-level event evidence has been observed yet."/>:null}</section>}
 {tab==='consent'&&<section className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><InsightCard title="CMP detection" value={consent.cmp?.name||'Not detected'} note={consent.cmp?.detected?`${fmt(consent.cmp.observations)} consent-state observations.`:'The current telemetry does not identify a CMP provider.'}/><InsightCard title="Consent mode detection" value={consent.consentMode?.detected?'Detected':'Not detected'} note={consent.consentMode?.detected?`${fmt(consent.consentMode.sessions)} sessions carried a consent-mode signal.`:'No consent-mode signal has been observed in the current window.'}/><InsightCard title="Choice recorded" value={consent.choiceRecorded?.percent==null?'Collecting evidence':`${consent.choiceRecorded.percent}% of sessions`} note={consent.choiceRecorded?.percent==null?'A precise choice rate is not supported by the current telemetry.':`${fmt(consent.choiceRecorded.sessions)} sessions have an explicit recorded choice.`}/></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="mb-4"><h3 className="text-sm font-semibold">Events firing outside consent</h3><p className="mt-1 text-xs text-[var(--text-3)]">Events observed before a consent choice or while required storage is denied are surfaced as issues for review.</p></div><Table><thead><tr><Th>Status</Th><Th>Event Name</Th><Th>Compliant</Th><Th>Vendor / GTM</Th><Th>Notes</Th></tr></thead><tbody>{consentIssues.map((r:any,i:number)=><tr key={`${r.event_name}-${i}`}><Td><StatusPill status={r.compliant?'Healthy':'Needs attention'}/></Td><Td><span className="font-mono text-xs">{r.event_name}</span></Td><Td><span className={`grid h-6 w-6 place-items-center rounded-full text-xs font-bold ${r.compliant?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{r.compliant?'✓':'×'}</span></Td><Td><div className="text-[11px] font-semibold">{r.vendor||vendor}</div><div className="text-[10px] text-[var(--text-3)]">{r.gtm_tag_name||'No GTM tag matched'}</div></Td><Td><span className="text-[11px] text-[var(--text-2)]">{r.notes||'Event was observed while consent was not established.'}</span></Td></tr>)}</tbody></Table>{!consentIssues.length?<Empty text="No vendor events were observed outside the consent evidence currently available."/>:null}</div></section>}
 {tab==='adblocks'&&<section className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Kpi label="Total Events" value={fmt(adblocks.total)}/><Kpi label="Successful events" value={fmt(adblocks.successful)} tone="ok"/><Kpi label="Blocked events" value={fmt(adblocks.blocked)} tone="warn"/></div><Panel title="Successful vs blocked events"><div className="mb-3 flex items-center justify-end"><FilterSelect label="Event name" value={adblockEventFilter} values={adblockEventNames} onChange={setAdblockEventFilter}/></div><LineGraph points={traffic}/></Panel><Table><thead><tr><Th>Status</Th><Th>Event Name</Th><Th>Blocked Events</Th><Th>Sessions</Th><Th>Notes</Th></tr></thead><tbody>{filteredBlocked.map((r:any)=><tr key={r.event_name}><Td><StatusPill status="Blocked"/></Td><Td><span className="font-mono text-xs">{r.event_name||'Unnamed event'}</span></Td><Td><span className="text-xs font-semibold">{fmt(r.blocked)}</span></Td><Td><span className="text-xs">{fmt(r.sessions)}</span></Td><Td><span className="text-[11px] text-[var(--text-2)]">{r.notes}</span></Td></tr>)}</tbody></Table>{!filteredBlocked.length?<Empty text="No confirmed or likely ad-blocker impact was observed for this platform."/>:null}</section>}
 </div>;
}
function Kpi({label,value,tone='info'}:{label:string;value:any;tone?:'ok'|'warn'|'info'}){const color=tone==='ok'?'#16a34a':tone==='warn'?'#f59e0b':'#4f46e5';return<div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4" style={{borderTop:`3px solid ${color}`}}><div className="text-[10px] font-bold uppercase tracking-[0.11em] text-[var(--text-3)]">{label}</div><div className="mt-2 text-2xl font-semibold text-[var(--text)]">{value}</div></div>}
function HealthMetric({label,value,warn=false}:{label:string;value:string;warn?:boolean}){return<div className="rounded-xl bg-[var(--surface-2)] p-4"><div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[var(--text-3)]">{label}</div><div className="mt-2 text-xl font-semibold" style={{color:warn?'#b45309':'var(--text)'}}>{value}</div></div>}
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return<div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow)]"><div className="mb-4"><h3 className="text-sm font-semibold text-[var(--text)]">{title}</h3>{subtitle?<p className="mt-1 text-xs leading-5 text-[var(--text-3)]">{subtitle}</p>:null}</div>{children}</div>}
function InsightCard({title,value,note}:{title:string;value:string;note:string}){return<div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[var(--text-3)]">{title}</div><div className="mt-3 text-lg font-semibold text-[var(--text)]">{value}</div><p className="mt-2 text-[11px] leading-5 text-[var(--text-2)]">{note}</p></div>}
function SectionHeader({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return<div className="flex flex-col gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 md:flex-row md:items-end md:justify-between"><div><h3 className="text-sm font-semibold text-[var(--text)]">{title}</h3><p className="mt-1 text-xs text-[var(--text-3)]">{subtitle}</p></div><div className="flex flex-wrap items-center gap-2">{children}</div></div>}
function FilterSelect({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return<label className="flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-2.5 py-1.5"><span className="text-[9px] font-bold uppercase tracking-[0.08em] text-[var(--text-3)]">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="max-w-[170px] bg-transparent text-[11px] font-semibold text-[var(--text)] outline-none">{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function RadioFilter({value,values,onChange}:{value:string;values:string[];onChange:(v:string)=>void}){return<div className="flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-2.5 py-1.5">{values.map(v=><label key={v} className="flex items-center gap-1 text-[10px] text-[var(--text-2)]"><input type="radio" checked={value===v} onChange={()=>onChange(v)}/>{v}</label>)}</div>}
function Table({children}:{children:React.ReactNode}){return<div className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow)]"><table className="w-full min-w-[900px] border-collapse text-left">{children}</table></div>}
function Th({children}:{children:React.ReactNode}){return<th className="border-b border-[var(--border)] px-4 py-3 text-[9px] font-bold uppercase tracking-[0.1em] text-[var(--text-3)]">{children}</th>}
function Td({children}:{children:React.ReactNode}){return<td className="border-b border-[var(--border-soft)] px-4 py-3 align-middle">{children}</td>}
function StatusPill({status}:{status:string}){const config:Record<string,[string,string]>={Healthy:['#dcfce7','#166534'],'Needs attention':['#fef3c7','#92400e'],'New event':['#dbeafe','#1d4ed8'],Blocked:['#ffedd5','#c2410c']};const [background,color]=config[status]||['var(--surface-3)','var(--text-2)'];return<span className="inline-flex items-center rounded-full px-2.5 py-1 text-[9px] font-bold" style={{background,color}}>{status}</span>}
function Empty({text}:{text:string}){return<div className="rounded-2xl border border-dashed border-[var(--border-strong)] bg-[var(--surface)] p-8 text-center text-xs text-[var(--text-3)]">{text}</div>}
function EmptyState({title,text}:{title:string;text:string}){return<div className="mx-auto max-w-2xl rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-10 text-center"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm text-[var(--text-2)]">{text}</p></div>}
function LoadingState({label}:{label:string}){return<div className="mx-auto max-w-2xl rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-10 text-center text-sm text-[var(--text-2)]">{label}</div>}
function formatDuration(seconds:number){if(!seconds)return'—';const mins=Math.floor(seconds/60),secs=Math.round(seconds%60);return mins?`${mins}m ${secs}s`:`${secs}s`}
