'use client';

import { useState } from 'react';
import Link from 'next/link';
import AlertModal from './alert-modal';
import { Pill, timeAgo } from './ui';
import { eventDisplayName as friendlyEventDisplayName, eventTypeDisplay, plainAlertMessage } from './plain-language';

const color = (vendor: string) => vendor === 'gads' ? '#4285F4' : vendor === 'meta' ? '#1877F2' : vendor === 'bing' ? '#0AA3FF' : vendor === 'linkedin' ? '#0A66C2' : vendor === 'tiktok' ? '#111' : vendor === 'snapchat' ? '#F4D35E' : '#F59E0B';
const initials = (vendor: string, label: string) => vendor === 'ga4' ? '▥' : vendor === 'meta' ? '∞' : vendor === 'gads' ? '△' : vendor === 'bing' ? '■' : label.slice(0, 2);
const displayName = (e: any, vendor: string) => e.event_name ? friendlyEventDisplayName(e.event_name) : vendor === 'bing' ? 'Page loaded' : 'Page view';
const missing = (e: any) => {
  const vals = Array.isArray(e.missing_parameters) ? e.missing_parameters.flatMap((v: any) => Array.isArray(v) ? v : []) : [];
  const labels: Record<string, string> = { id: 'pixel_id', ev: 'event_name', pid: 'partner_id', pids: 'pixel_id', ti: 'uet_tag_id', tag_id: 'uet_tag_id', tid: 'conversion_id' };
  return [...new Set(vals.filter(Boolean).map((v: string) => labels[v] || v))];
};

export default function VendorUI({ vendor, label, id, siteId, data }: { vendor: string; label: string; id: string | null; siteId: string; data: any }) {
  const [tab, setTab] = useState('overview');
  const [filter, setFilter] = useState('All');
  const [search, setSearch] = useState('');
  const [alert, setAlert] = useState<any>(null);
  const events = data.events || [];
  const alerts = (data.alerts || []).filter((a: any) => !a.vendor || a.vendor === vendor);
  const stats = data.stats || {};
  const total = events.reduce((n: number, e: any) => n + Number(e.cnt || 0), 0);
  const blocked = Number(stats.adblock_24h || 0);
  const pct = total ? (blocked / total) * 100 : 0;
  const details = events.filter((e: any) => Array.isArray(e.parameter_statuses) && e.parameter_statuses.length);
  const filtered = events.filter((e: any) => {
    const a = alerts.find((x: any) => x.event_name === e.event_name);
    const s = a?.severity === 'critical' ? 'Needs attention' : a ? 'Worth checking' : e.is_new ? 'New Event' : 'Info';
    return (filter === 'All' || filter === s) && `${displayName(e, vendor)} ${e.event_name || ''}`.toLowerCase().includes(search.toLowerCase());
  });
  const destinations = [
    ['Google Analytics 4', 'ga4', '/dashboard/ga4'], ['Google Ads', 'gads', '/dashboard/ads'], ['Meta', 'meta', '/dashboard/meta'], ['Microsoft Ads', 'bing', '/dashboard/bing']
  ];
  const tabs = [['overview','Overview',events.length+1],['events','Events',events.length],['details','Event details',details.length],['pages','Pages',0],['consent','Consent',0],['adblocks','Ad blockers',pct.toFixed(1)+'%']];

  return <div className="fade-in mx-auto max-w-[1500px]">
    <div className="mb-3 flex items-start justify-between"><div><h2 className="font-display text-[20px] font-semibold text-[var(--text)]">shop.example.com</h2><p className="text-[10px] text-[var(--text-3)]">Production · GA4 + GTM · last sweep 4 min ago</p><p className="text-[10px] text-[var(--text-3)]">3 of 6 connections healthy, 1 needs a look.</p></div><div className="flex gap-2"><button className="rounded-full border border-[var(--border)] px-4 py-2 text-[10px]">Last 14 days</button><Link href={`/dashboard/install?siteId=${siteId}`} className="rounded-full bg-[#f97316] px-4 py-2 text-[10px] font-semibold text-white">Manage script</Link></div></div>
    <div className="mb-4"><div className="mb-2 flex items-center gap-2"><b className="text-[12px]">Destinations</b><span className="text-[10px] text-[var(--text-3)]">3 active · 1 warning · 3 not connected</span></div><div className="flex gap-2 overflow-x-auto">
      {destinations.map(([name,v,path]) => <Link key={name} href={`${path}?siteId=${siteId}`} className="min-w-[165px] flex-1 rounded-[10px] border bg-[var(--surface)] p-2.5" style={{borderColor: vendor===v ? '#f97316' : 'var(--border)'}}><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg" style={{background:color(v)+'18',color:color(v)}}>{initials(v,name)}</span><div><div className="text-[10px] font-semibold">{name} ›</div><div className="text-[9px] text-[var(--ok-fg)]">{vendor===v?'Active':'Active'}</div></div></div><div className="mt-1.5 flex justify-between text-[9px]"><span className="rounded-full bg-[#fff4df] px-2 py-0.5 text-[#b76b00]">{vendor===v?alerts.length:1} things to check</span><span>Edit</span></div></Link>)}
      {['TikTok','LinkedIn','Snapchat'].map(n=><div key={n} className="grid min-w-[65px] place-items-center rounded-[10px] border border-[var(--border)] p-2.5 text-[9px]"><b>{n==='LinkedIn'?'in':n==='TikTok'?'♪':'◉'}</b><span className="text-[9px] text-[var(--text-3)]">Add</span></div>)}
    </div></div>
    <div className="flex items-center gap-3"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg" style={{background:color(vendor)+'18',color:color(vendor)}}>{initials(vendor,label)}</span><h1 className="font-display text-[17px] font-semibold">{label}</h1></div><div className="flex min-w-0 flex-1 items-center rounded-[9px] border border-[var(--border)] px-3 py-2"><span className="mr-2">⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Example: name:purchase label: #ecommerce" className="min-w-0 flex-1 bg-transparent text-[10px] outline-none"/><span>⌄</span></div><button className="rounded-full border px-3 py-2 text-[9px]">Filter warnings</button><button className="rounded-full border px-3 py-2 text-[9px]">Share</button></div>
    <p className="mt-1 text-[9px] text-[var(--text-3)]">Search for a specific event, like "purchase" or "signup" — optional.</p><p className="mt-1 text-[9px] text-[var(--text-3)]">Gain insight into what this destination is receiving, and where the data breaks. <span className="text-[#f97316]">Learn more.</span></p>
    <div className="mt-3 flex gap-5 overflow-x-auto border-b border-[var(--border)]">{tabs.map(([k,n,c])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap border-b-2 px-1 pb-2.5 text-[10px] font-semibold ${tab===k?'border-[var(--text)] text-[var(--text)]':'border-transparent text-[var(--text-3)]'}`}>{n} ({c}) <span className="rounded-full bg-[#fff0e7] px-1.5 py-0.5 text-[#d95f18]">{k==='adblocks'?c: k==='overview'?alerts.length:k==='details'?details.filter((e:any)=>missing(e).length).length:0}</span></button>)}</div>
    <p className="py-2 text-[9px] text-[var(--text-3)]">{tab==='overview'?'A quick health check for this platform — is your data flowing the way it should?':tab==='events'?'Every action visitors take that gets tracked, like purchases, signups, and clicks.':tab==='details'?'The extra details attached to each event, like which product was bought or which button was clicked.':tab==='pages'?"Which pages on your site are sending data correctly, and which aren't.":tab==='consent'?"Whether visitors' cookie consent choices are being tracked and respected.":'How many visitors have ad blockers, which can hide some of your data from you.'}</p>
    {tab==='overview' && <><div className="mb-3 rounded-[10px] border bg-[var(--surface)] p-3"><div className="grid gap-2 md:grid-cols-[100px_1fr]"><div className="grid place-items-center"><div className="grid h-14 w-14 place-items-center rounded-full border-[6px] border-green-500 text-[9px] font-bold">HEALTH<br/>{Math.max(0,100-alerts.length*8)}%</div></div><div className="grid grid-cols-2 gap-2 md:grid-cols-3"><Metric label="hits" value={total.toLocaleString()} tone="ok"/><Metric label="events" value={events.length} tone="ok"/><Metric label="properties" value={details.length || '—'} tone="ok"/><Metric label="New issues" value={alerts.length} tone="warn"/><Metric label="Still open" value={alerts.length} tone="warn"/><Metric label="New event type detected" value={events.filter((e:any)=>e.is_new).length} tone="info"/></div></div></div><Warnings alerts={alerts} onSelect={setAlert}/></>}
    {tab==='events' && <Table title="Events" count={filtered.length} search="Search event name — select several"><div className="flex flex-wrap gap-1.5 border-b px-4 py-3"><span className="mr-1 text-[8px] font-semibold">STATUS</span>{['All','Info','Needs attention','Worth checking','New Event'].map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-full border px-2.5 py-1 text-[9px] ${filter===s?'border-[#f97316] text-[#f97316]':''}`}>{s}</button>)}</div>{filtered.map((e:any,i:number)=><EventRow key={i} e={e} vendor={vendor} alert={alerts.find((a:any)=>a.event_name===e.event_name)}/>)}</Table>}
    {tab==='details' && <Table title="Event details" count={details.length} search="Search parameters — select several">{details.length?details.flatMap((e:any)=>missing(e).length?missing(e).map((n:string,i:number)=><div key={n+i} className="grid grid-cols-4 border-b px-4 py-3 text-[9px]"><Pill tone="crit" dot={false}>Needs attention</Pill><span className="font-mono">{n}</span><span className="text-red-500">Missing · 41%</span><span className="text-[var(--text-3)]">Missing on {displayName(e,vendor)}</span></div>):<div className="grid grid-cols-4 border-b px-4 py-3 text-[9px]"><Pill tone="ok" dot={false}>Info</Pill><span className="font-mono">parameters</span><span className="text-green-600">Complete · 100%</span><span className="text-[var(--text-3)]">Present on {displayName(e,vendor)}</span></div>):<Empty text="No event-detail data is available from the current tracking response."/>}</Table>}
    {tab==='pages' && <Table title="Pages" count={0} search="Search page name — select several"><Empty text="Page-level data is not returned by the current events endpoint."/></Table>}
    {tab==='consent' && <div className="rounded-[10px] border bg-[var(--surface)] p-6"><b className="text-[12px]">Consent monitoring</b><p className="mt-1 text-[10px] text-[var(--text-3)]">Consent details are not returned by the current tracking endpoint. No consent logic has been changed.</p></div>}
    {tab==='adblocks' && <><div className="grid gap-3 md:grid-cols-3"><Metric label="Total events" value={total.toLocaleString()} tone="info"/><Metric label="Successful events" value={Math.max(0,total-blocked).toLocaleString()} tone="ok"/><Metric label="Blocked events" value={blocked.toLocaleString()} tone="warn"/></div><div className="my-3 rounded-[10px] border bg-[var(--surface)] p-4"><b className="text-[12px]">Impact of ad blockers</b><div className="mt-3 flex h-6 overflow-hidden rounded"><div className="grid place-items-center bg-[#4f46e5] text-[9px] font-semibold text-white" style={{width:`${Math.max(0,100-pct)}%`}}>Delivered {(100-pct).toFixed(1)}%</div><div className="grid place-items-center bg-[#f97316] text-[9px] font-semibold text-white" style={{width:`${pct}%`}}>{pct.toFixed(1)}%</div></div></div></>}
    <AlertModal alert={alert} onClose={()=>setAlert(null)}/>
  </div>;
}

function Metric({label,value,tone}:{label:string;value:any;tone:'ok'|'warn'|'info'}) { const c=tone==='ok'?'#16a34a':tone==='warn'?'#f59e0b':'#4f46e5'; return <div className="rounded-lg border bg-[var(--surface)] px-3 py-2" style={{borderBottom:`2px solid ${c}`}}><div className="text-[8px] text-[var(--text-3)]">{label}</div><div className="text-[16px] font-semibold">{value}</div></div>; }
function Table({title,count,search,children}:{title:string;count:any;search:string;children:any}) { return <div className="overflow-hidden rounded-[10px] border bg-[var(--surface)]"><div className="flex justify-between border-b px-4 py-3"><b className="text-[12px]">{title} <span className="font-normal text-[var(--text-3)]">{count} shown</span></b><span className="rounded-lg border px-3 py-2 text-[9px] text-[var(--text-3)]">⌕ {search}</span></div>{children}</div>; }
function EventRow({e,vendor,alert}:{e:any;vendor:string;alert:any}) { const status=alert?.severity==='critical'?'Needs attention':alert?'Worth checking':e.is_new?'New Event':'Info'; const tone=status==='Needs attention'?'crit':status==='Worth checking'?'warn':status==='New Event'?'info':'ok'; return <div className="grid grid-cols-4 items-center border-b px-4 py-3 text-[9px]"><Pill tone={tone as any} dot={false}>{status}</Pill><div><div className="font-mono text-[10px]">{displayName(e,vendor)}</div><span className="rounded-full bg-[var(--surface-3)] px-1.5 py-0.5 text-[8px]">{eventTypeDisplay(e.event_type)}</span></div><b>{Number(e.cnt||0).toLocaleString()} <span className="font-normal text-[var(--text-3)]">{Number(e.sessions||0).toLocaleString()}</span></b><span className="text-[var(--text-3)]">{alert?plainAlertMessage(alert):e.is_new?`First seen ${timeAgo(e.first_seen||e.created_at)}`:'Nothing to flag'}</span></div>; }
function Warnings({alerts,onSelect}:{alerts:any[];onSelect:(a:any)=>void}) { return <div className="overflow-hidden rounded-[10px] border bg-[var(--surface)]"><div className="flex justify-between border-b px-4 py-3"><div><b className="text-[12px]">Warnings</b><div className="mt-1 text-[9px] text-[var(--text-3)]">All ({alerts.length}) · Ongoing · Muted · Resolved</div></div><button className="rounded-full border px-3 py-1.5 text-[9px]">Filter</button></div>{alerts.length?alerts.slice(0,8).map((a:any)=><button key={a.id} onClick={()=>onSelect(a)} className="grid w-full grid-cols-[1fr_150px_1fr] border-b px-4 py-3 text-left"><div><div className="text-[8px] font-semibold uppercase text-[#e05252]">● {a.category||a.code||'warning'}</div><b className="text-[10px]">{friendlyEventDisplayName(a.event_name||a.code||'Tracking issue')}</b><p className="mt-1 text-[9px] text-[var(--text-3)]">{plainAlertMessage(a)}</p></div><div className="text-[9px]">{timeAgo(a.created_at)}<div className="text-[8px] text-[var(--text-3)]">{a.occurrence_count||1} days active</div></div><div className="text-[9px] italic text-[var(--text-3)]">{a.root_cause||'Add info to monitor warning management progress'} ›</div></button>):<Empty text="No active warnings."/>}</div>; }
function Empty({text}:{text:string}) { return <div className="p-8 text-center text-[10px] text-[var(--text-3)]">{text}</div>; }
